trigger:
- pull_request

pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration Release
  displayName: 'Build solution'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    arguments: '--configuration Release'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish RagChat and RagChatFrontend'
  inputs:
    command: publish
    projects: '**/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
